apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.appSecretName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
