"""add_job_type_and_fix_job_indices

Revision ID: 508a085e1e1f
Revises: 0001_initial
Create Date: 2026-05-24 08:17:39.828726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '508a085e1e1f'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_type', sa.String(length=32), nullable=False))
    op.alter_column('jobs', 'cron_expression',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('jobs', 'next_fire_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.alter_column('jobs', 'next_fire_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('jobs', 'cron_expression',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('jobs', 'job_type')
    # ### end Alembic commands ###

