{{- $primaryUrl := printf "postgresql+psycopg://%s:%s@%s:5432/%s" .Values.postgres.auth.username .Values.postgres.auth.password (include "meta-chart.postgresHost" .) .Values.postgres.auth.database -}}
{{- $replicaUrl := printf "postgresql+psycopg://%s:%s@%s:5432/%s" .Values.postgres.auth.username .Values.postgres.auth.password (include "meta-chart.postgresReplicaHost" .) .Values.postgres.auth.database -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meta-chart.backendSecretName" . }}
  labels:
    {{- include "meta-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  DASS_DATABASE_URL: {{ $primaryUrl | quote }}
  DASS_REPLICA_DATABASE_URL: {{ ternary $replicaUrl $primaryUrl (gt (int .Values.postgres.instances) 1) | quote }}
  DASS_AWS_ACCESS_KEY_ID: {{ .Values.global.app.awsAccessKeyId | quote }}
  DASS_AWS_SECRET_ACCESS_KEY: {{ .Values.global.app.awsSecretAccessKey | quote }}
