apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "meta-chart.frontendConfigName" . }}
  labels:
    {{- include "meta-chart.labels" . | nindent 4 }}
data:
  DASS_BACKEND_URL: {{ .Values.global.frontend.backendUrl | quote }}
