global:
  frontend:
    backendUrl: http://api-server:80

postgres:
  instances: 2
  storage:
    storageClassName: ceph-rbd

localstack:
  persistence:
    storageClassName: ceph-rbd

api-server:
  spreadAcrossNodes: true
  rollout:
    enabled: true
  service:
    type: LoadBalancer
    port: 80
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

worker:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  autoscaling:
    enabled: false
  keda:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 10
    queueLength: "5"
    awsRegion: us-east-1
    awsEndpoint: ""
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: dass.io/docker-sock
                operator: In
                values:
                  - "true"

frontend:
  spreadAcrossNodes: true
  rollout:
    enabled: true
  service:
    type: LoadBalancer
    port: 80
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
