{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "worker.fullname" . }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: {{ include "worker.fullname" . }}-sqs-auth
      metadata:
        queueURLFromEnv: {{ .Values.keda.queueURLFromEnv | quote }}
        queueLength: {{ .Values.keda.queueLength | quote }}
        awsRegion: {{ .Values.keda.awsRegion | quote }}
        awsEndpoint: {{ .Values.keda.awsEndpoint | default (printf "http://localstack.%s.svc.cluster.local:4566" .Release.Namespace) | quote }}
{{- end }}
